### ISSUE TITLE
Issue another release?

### ISSUE THREAD

**Issue by squatto** [permafrost-dev/node-ray-cli#101]
Would it be possible to get another release pushed out so that the latest changes make it into yarn/npm? Selfishly, I just want it so that I can do `ray confetti` from my cli scripts 😉 

Thank you!

**Comment by patinthehat** [comment]
@squatto Absolutely!  I'll take care of this shortly, stand by.  Thanks for the reminder! :+1:

**Comment by patinthehat** [comment]
@squatto I've released v1.1.0, which incorporates a bunch of dep updates, as well as a few new commands such as `confetti`.  See [release notes for v1.1.0](https://github.com/permafrost-dev/node-ray-cli/releases/tag/v1.1.0).  Thanks again for the reminder :+1:

**Comment by squatto** [comment]
Thank you very much @patinthehat!
